### ISSUE TITLE
请问能否增加https支持?

### ISSUE THREAD

**Issue by i21314049** [maomao1996/Vue-mmPlayer#10]
启用https后,获取的封面图片都是http的,请问如何修改才能让获取的歌曲封面也是https的链接呢

**Comment by maomao1996** [comment]
你好，获取歌单详情接口返回的封面图片是 http ，歌曲详情接口的封面图片是 https的，全部改为https，你只需要这样替换下就行了，
``` js
封面url.replace('http://', 'https://')
```
