### ISSUE TITLE
How to build mobile apps from web source code?

### ISSUE THREAD

**Issue by diepdo1810** [maomao1996/Vue-mmPlayer#112]
Thanks for reading.

I'm trying build mobile app from web source code using [capacitorjs](https://capacitorjs.com/). 

Everything works but one problem is that music cannot be played. I tried to find out if the cause could be related to permissions or missing plugins. It seems like there's a deadlock. If anyone has ever used the above library and deployed from Vue to mobile application. Then let me know. 

Thanks a lot.

**Comment by maomao1996** [comment]
NetEase Cloud Music's backend services experienced issues this afternoon
