### ISSUE TITLE
询问音频播放问题

### ISSUE THREAD

**Issue by JingFanWang** [maomao1996/Vue-mmPlayer#27]
请问在网页引用audio标签后，播放音频可能会出现 Uncaught (in promise) DOMException(谷歌浏览器) ，应该怎么解决这个问题

**Comment by maomao1996** [comment]
你好，最新的提交已修复这个问题，具体请看此次[代码提交](https://github.com/maomao1996/Vue-mmPlayer/commit/91bfde37453842b35939a82b69b6e5e94fc5cbba)
问题原因：
chrome 从 50 版本开始 `HTMLMediaElement.play()` 会返回一个 `Promise`
当成功开始播放后，会将 `Promise` 状态设置为 `resolved`
当因为其他原因而无法开始播放时，会将 `Promise` 状态设置为 `rejected`
众所周知当 `rejected` 状态的 `Promise` 没有被 `catch` 时就会提示 `Uncaught (in promise) ...`
参考资料：
[chrome - HTMLMediaElement.play() Returns a Promise](https://developers.google.com/web/updates/2016/03/play-returns-promise)
兼容性查询：
[MDN - HTMLMediaElement.play() Returns a Promise](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play)

**Comment by JingFanWang** [comment]
我根据你的 MDN - HTMLMediaElement.play() Returns a Promise链接 修改了代码，现在是不报Uncaught (in promise) DOMException 这个错误了，但是音频还是无法播放

**Comment by JingFanWang** [comment]
![image](https://user-images.githubusercontent.com/48482482/72067609-1efaa680-331e-11ea-88ea-b608b707d39b.png)

**Comment by maomao1996** [comment]
你代码有问题吧，我试过都是可以的  [MDN 例子](https://codesandbox.io/s/confident-pike-u82it)
