### ISSUE TITLE
您好请问是纯前端的项目吗

### ISSUE THREAD

**Issue by AnhTom2000** [maomao1996/Vue-mmPlayer#29]
已经star了您的项目，刚学完vue想找个项目练练手

**Comment by maomao1996** [comment]
你好，这个项目不是个纯前端项目，是有后台的 [网易云音乐 NodeJS 版 API](https://binaryify.github.io/NeteaseCloudMusicApi/#/) ,只需要把这个后台拉下来启动 node 服务就行了

**Comment by AnhTom2000** [comment]
好的，感谢您的回答

**Comment by AnhTom2000** [comment]
> 你好，这个项目不是个纯前端项目，是有后台的 [网易云音乐 NodeJS 版 API](https://binaryify.github.io/NeteaseCloudMusicApi/#/) ,只需要把这个后台拉下来启动 node 服务就行了
好的，感谢您的回答
