### ISSUE TITLE
音乐暂停后播放问题

### ISSUE THREAD

**Issue by Joarn** [maomao1996/Vue-mmPlayer#33]
音乐暂停一段时间后，点击播放，会显示音乐无法播放，然后自动跳转到下一首，需要重新切换回来。

**Comment by maomao1996** [comment]
你好，该问题已在 [1.6.6](https://github.com/maomao1996/Vue-mmPlayer/commit/2d62af977a83f358d704766a3e0401fc2424d66d) 版本中修复

**Comment by Joarn** [comment]
好的，感谢你的这个项目。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"茂茂"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 晚上10:06
收件人:&nbsp;"maomao1996/Vue-mmPlayer"<Vue-mmPlayer@noreply.github.com&gt;;
抄送:&nbsp;"1311080574"<1311080574@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maomao1996/Vue-mmPlayer] 音乐暂停后播放问题 (#33)





 
你好，该问题已在 1.6.6 版本中修复
