### ISSUE TITLE
拖动音乐进度条，声音会有快进似的杂音。

### ISSUE THREAD

**Issue by huxiaocheng** [maomao1996/Vue-mmPlayer#34]

**Comment by maomao1996** [comment]
目前的实现是播放进度跟拖动进度实时同步的，所以会有这种情况，后续我优化下

**Comment by maomao1996** [comment]
该问题已在 [1.6.7](https://github.com/maomao1996/Vue-mmPlayer/commit/6dafb876a3259e844da557aee7ecd1f72d59139f) 版本中修复
