### ISSUE TITLE
手机端显示歌词

### ISSUE THREAD

**Issue by tangkuna** [maomao1996/Vue-mmPlayer#36]
想用您的作品把妹，自己修改了一些，都挺满意，只是大佬能否在手机端显示下歌词呢。虽然自己改了能显示歌词，但是奈何自己技术有限，并不好看

**Comment by maomao1996** [comment]
之前已经在弄了，应该就这几天发布，至于界面的话我也没啥好的想法，毕竟做自适应有点碍手碍脚
（话说这也能把妹吗，优秀）

**Comment by tangkuna** [comment]
敢想，敢做(哭笑)，只是自己技术太差(哭)

**Comment by maomao1996** [comment]
1.7.0 版本已增加移动端增加歌词显示
