### ISSUE TITLE
移动端浏览器播放音乐，当前音乐播放完，不会自动播放下一首

### ISSUE THREAD

**Issue by tangkuna** [maomao1996/Vue-mmPlayer#39]
不懂就问：用移动端的浏览器播放音乐时，如果离开当前播放页面，或者浏览器后台运行，当音乐播放完，不会自动播放下一首。除非重新回到播放页，或者进入浏览器，才会自动播放下一曲。想咨询下大佬这是什么原因，是移动端浏览器禁止自动播放了吗？能解决吗？要怎么解决？

**Comment by maomao1996** [comment]
没啥好解决的，移动端就这样的策略，在后台的时候代码没有执行，所以你就切换不了音频了
