### ISSUE TITLE
/top/list 接口提示 Requset failed with status code 500

### ISSUE THREAD

**Issue by maomao1996** [maomao1996/Vue-mmPlayer#41]
问题: 下载代码后运行项目提示 `Requset failed with status code 500`

原因: [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 在 v3.34.0 版本之后 `/top/list` 接口不再支持`idx` 参数 [排行榜接口废弃 idx 参数,只支持 id 参数](https://github.com/Binaryify/NeteaseCloudMusicApi/commit/885d1930f2bd351576817e9c19102c62f0a270e8)

修复方案一: 修改 `api` 文件中的 `topList` 方法参数为 `id`
修复方案二: 后台服务版本降级使用 [NeteaseCloudMusicApi v3.33.2](https://github.com/Binaryify/NeteaseCloudMusicApi/tree/v3.33.2)

**Comment by h7ml** [comment]
茂茂666

**Comment by wnark** [comment]
补充下是修改播放器Vue-mmPlayer的路径下
`src/api/index.js`
将排行榜详情的idx改成id，然后重新build，重新把dist文件夹搬过去。
