### ISSUE TITLE
登录后播放“我的歌单”时重复“无法播放，播放下一首”

### ISSUE THREAD

**Issue by Thundercup** [maomao1996/Vue-mmPlayer#42]

**Comment by maomao1996** [comment]
你好，能提供下歌单 id 吗

**Comment by Thundercup** [comment]
257280652

**Comment by maomao1996** [comment]
无法播放，播放下一首，是因为网抑云木有版权所以不能播放，比如这个歌单有些歌曲显示就是灰色的 https://music.163.com/#/playlist?id=150032455 ，不过我这边没有做无版权歌曲的标识

**Comment by Thundercup** [comment]
但我是从第一首开始播放，不应该出现这种问题，因为第一首是有版权的

**Comment by maomao1996** [comment]
我这边的登录只是通过 uid 去获取公开数据，而你的这个歌单（https://music.163.com/#/playlist?id=2376279632）都是 VIP 歌曲没有开放的，所以会有这个情况
