### ISSUE TITLE
点击歌单时，报错Network Error。

### ISSUE THREAD

**Issue by callng** [maomao1996/Vue-mmPlayer#43]
感觉是这个歌单太多了 ，[歌单 453553114](https://music.163.com/#/my/m/music/playlist?id=453553114)。

程序一次加载的歌单歌曲太多，我喜欢（歌单 453553114 默认收藏歌单）已有740首歌曲 ，但是程序一次性就要获取740首歌曲的信息。

调用 API 时  GET 带的参数太多了（可能），我试过直接访问API，报错（提示连接已被关闭）

希望能优化下，如果歌单歌曲数很多，不要一次性加载完，下拉歌单内容时才获取剩下的歌单（瀑布加载）。

![Network Error](https://user-images.githubusercontent.com/64207250/89096227-a79a7a80-d407-11ea-9289-d02bd0a1c739.png)

![报错](https://user-images.githubusercontent.com/64207250/89096238-c00a9500-d407-11ea-8fd7-80583fababb3.png)

**Comment by maomao1996** [comment]
好的，这个后续版本会优化
