### ISSUE TITLE
一开始进入页面时候的每首歌曲的时长是从哪个接口来的，或者是怎么算的

### ISSUE THREAD

**Issue by chenchunyang123** [maomao1996/Vue-mmPlayer#44]
我找了半天还是没找到相关内容

**Comment by maomao1996** [comment]
都是接口返回的，具体可以看[代码](https://github.com/maomao1996/Vue-mmPlayer/blob/master/src/utils/song.js#L30)，分别是 `duration` 和 `dt` 字段

**Comment by chenchunyang123** [comment]
好的，非常感谢
