### ISSUE TITLE
[Feature Request] 添加鲸鱼音效

### ISSUE THREAD

**Issue by qinyuanqiblog** [maomao1996/Vue-mmPlayer#46]
最近在做音乐播放器，然后就找到了大佬的这个项目，又可以愉快的cv 了， 然后看到有个阿里的大佬写了个鲸鱼音效，觉得加到这个项目挺不错的哈，😃😃😃
https://github.com/alex2wong/vudio

**Comment by maomao1996** [comment]
感谢建议😃，后续全新版本会加入音频可视化的

**Comment by qinyuanqiblog** [comment]
优秀 👏👏👍👍
