### ISSUE TITLE
推荐列表下，云音乐特色榜含有更新频率字段，但热门歌单中无此字段

### ISSUE THREAD

**Issue by wangkangzhen** [maomao1996/Vue-mmPlayer#49]

**Comment by maomao1996** [comment]
特色榜是官方维护的，热门歌单不是

**Comment by wangkangzhen** [comment]
回复的真快~
悬浮的时候显示undefined，可以看下截图~

![image](https://user-images.githubusercontent.com/22878303/97950599-5e751080-1dd2-11eb-9358-05c17a9fea8c.png)

已经提交了PR，可以看下。

**Comment by wangkangzhen** [comment]
响应迅速，给个赞

**Comment by maomao1996** [comment]
😃 已重新部署，感谢
