### ISSUE TITLE
你好，请问js写的HTML是哪个文件呢！

### ISSUE THREAD

**Issue by ShenGunNiTian** [maomao1996/Vue-mmPlayer#5]

**Comment by maomao1996** [comment]
是挂载的html文件吗？还是啥

**Comment by ShenGunNiTian** [comment]
类似于这些，就是返回页面，有数据等等，我不知道怎么表达。。。
function addListhead() {
    var html = '<div class="list-head">' +
    '    <span class="music-duration">' +
    '        时长' +
    '    </span>' +
    '    <span class="music-album">' +
    '        专辑' +
    '    </span>' +
    '    <span class="auth-name">' +
    '        歌手' +
    '    </span>' +
    '    <span class="music-name">' +
    '        歌曲' +
    '    </span>' +
    '</div>';
    rem.mainList.append(html);
}

**Comment by ShenGunNiTian** [comment]
<span class="music-name">这个不见了，不知道你那边可不可以看到

**Comment by ShenGunNiTian** [comment]
那些前端代码不见了，可能不让显示

**Comment by maomao1996** [comment]
[Vue](https://cn.vuejs.org/) 了解一下

**Comment by ShenGunNiTian** [comment]
谢谢了，不过我是用其他语言开发的。想借鉴一下一些页面的布局

**Comment by maomao1996** [comment]
你可以去看qq音乐PC版，我界面借鉴的他的

**Comment by ShenGunNiTian** [comment]
看过qq音乐的，搜索想改成你这样的 ，所以想请教你一下。（http://112.74.61.42）

**Comment by maomao1996** [comment]
先把搜索界面写好，再把JQ写的打开弹窗的事件改成切换搜索页面的就行了

**Comment by ShenGunNiTian** [comment]
好的，谢谢。因为这样的搜索播放一首歌之后，再想播放搜索的，就会重新搜索了，还是你的这个体验比较好。还有就是，弹窗事件改了之后，那个搜索列表是不是和你这个一样了，还是会有其他什么的。

**Comment by maomao1996** [comment]
这个就要看你的布局怎么写了

**Comment by maomao1996** [comment]
是的，先找到播放列表的这首歌对应的index，再splice掉

**Comment by ShenGunNiTian** [comment]
是那个js文件呢，我想看一下

**Comment by maomao1996** [comment]
注释是[//删除正在播放列表中的歌曲](https://github.com/maomao1996/Vue-mmPlayer/blob/master/src/store/actions.js) 这个是Vuex，不知道你能不能看懂

**Comment by ShenGunNiTian** [comment]
可以了解了解。。。
