### ISSUE TITLE
可以接入HASS播放，就是没声音

### ISSUE THREAD

**Issue by hxfdean** [maomao1996/Vue-mmPlayer#53]
大佬，我按文档接入了hass，云音乐标签可以搜索，可以选歌播放，登陆也正常，但是播放没有声音。
我是在hass的树莓派上运行的云api服务，和hass是同一台机器。
异常点在于hass的 “概览” 标签界面的“云音乐”卡片点开右上角三个点，只有“详情”和“历史”两个按钮，点击设置齿轮出现：该实体 ("media_player.yun_yin_le") 没有唯一的 ID，因此无法由 UI 管理其设置。请参阅 文档 以详细了解。 也就是说没有选择播放器的选项，音量调节，进度条等，也没有语音助手等 B站视频演示的那些东西。
求救求救，最后一步就成功，麻烦大佬拯救下。
感谢，感谢，感谢！

以下是我configation配置

media_player:
  - platform: ha_cloud_music
    api_url: 'http://localhost:3000'
    sidebar_title: 云音乐
    sidebar_icon: mdi:music
    show_mode: fullscreen
    uid: 414728269
    user: 1872*******
    password: d*******
    tts_before_message: '主人：'
    tts_after_message: '。我是你的家居管家!'
    tts_mode: 4
    is_voice: true
    is_notify: true
    is_debug: true
    mpd_host:

**Comment by maomao1996** [comment]
hass 是什么我都不知道，这个我也无能为力，还有能不能正常播放你要 f12 看控制台的信息看看音频资源加载情况，代码是否报错，不能光看有没有声音




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maomao1996/Vue-mmPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 上午10:08
收件人:&nbsp;"maomao1996/Vue-mmPlayer"<Vue-mmPlayer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[maomao1996/Vue-mmPlayer] 可以接入HASS播放，就是没声音 (#53)





 
大佬，我按文档接入了hass，云音乐标签可以搜索，可以选歌播放，登陆也正常，但是播放没有声音。
 我是在hass的树莓派上运行的云api服务，和hass是同一台机器。
 异常点在于hass的 “概览” 标签界面的“云音乐”卡片点开右上角三个点，只有“详情”和“历史”两个按钮，点击设置齿轮出现：该实体 ("media_player.yun_yin_le") 没有唯一的 ID，因此无法由 UI 管理其设置。请参阅 文档 以详细了解。 也就是说没有选择播放器的选项，音量调节，进度条等，也没有语音助手等 B站视频演示的那些东西。
 求救求救，最后一步就成功，麻烦大佬拯救下。
 感谢，感谢，感谢！
 
以下是我configation配置
 
media_player:
  
platform: ha_cloud_music
 api_url: 'http://localhost:3000'
 sidebar_title: 云音乐
 sidebar_icon: mdi:music
 show_mode: fullscreen
 uid: 414728269
 user: 1872*******
 password: d*******
 tts_before_message: '主人：'
 tts_after_message: '。我是你的家居管家!'
 tts_mode: 4
 is_voice: true
 is_notify: true
 is_debug: true
 mpd_host:

**Comment by hxfdean** [comment]
感谢大佬，控制台没有报错，进度条时间也正常走，但是不知道为什么，没有声音出来，上面说的选择播放器界面出来了，是没有清空缓存刷新导致的，但是，还是没有声音，试了从mpd播放，mpd的服务端也能看见有新的mpd客户端链接，但是还是放不出声。。
顺便问下大佬，网页端怎么播放歌曲啊？

**Comment by hxfdean** [comment]
hass 就是 Home Assistant,我的错，偷懒了

**Comment by maomao1996** [comment]
那可能是歌曲格式的问题吧


怎么播放自己看这个吧&nbsp;https://www.runoob.com/tags/ref-av-dom.html







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maomao1996/Vue-mmPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 上午10:39
收件人:&nbsp;"maomao1996/Vue-mmPlayer"<Vue-mmPlayer@noreply.github.com&gt;;
抄送:&nbsp;"茂茂"<1714487678@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [maomao1996/Vue-mmPlayer] 可以接入HASS播放，就是没声音 (#53)





 
感谢大佬，控制台没有报错，进度条时间也正常走，但是不知道为什么，没有声音出来，上面说的选择播放器界面出来了，是没有清空缓存刷新导致的，但是，还是没有声音，试了从mpd播放，mpd的服务端也能看见有新的mpd客户端链接，但是还是放不出声。。
 顺便问下大佬，网页端怎么播放歌曲啊？

**Comment by corbettbain** [comment]
楼主解决这个问题了 吗 ， 同样遇到这个问题

**Comment by maomao1996** [comment]
> 楼主解决这个问题了 吗 ， 同样遇到这个问题

没有解决 0.0
