### ISSUE TITLE
提示Network Error

### ISSUE THREAD

**Issue by Li-xp** [maomao1996/Vue-mmPlayer#55]
网易云API正常运行，.env中链接已经修改，一进去就提示Network Error

**Comment by maomao1996** [comment]
自己看下控制台的信息，还有 api 项目的 log 打印

**Comment by Li-xp** [comment]
通过在Index.html中加入<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />解决了控制台输出This request has been blocked; the content must be served over HTTPS.错误的问题，但还是提示Network Error。

**Comment by maomao1996** [comment]
浏览器打开 api 的服务看看有没有启动好

**Comment by Li-xp** [comment]
API服务正常启动

**Comment by Li-xp** [comment]
分析控制台可以得出在运行过程中请求的接口地址为“域名:3000”，但是我在.env中写入的接口为"IP:3000"，就很奇怪

**Comment by maomao1996** [comment]
只要你浏览能够正常访问 api，env 中的地址和你的 api 服务地址一致就不会出现 Network Error

自己好好检查下哪里写的不对吧

**Comment by Li-xp** [comment]
问题已解决。为后端接口部署SSL
