### ISSUE TITLE
你好，请问歌曲的时长和播放条那的时间歌名歌手是写在哪个文件的

### ISSUE THREAD

**Issue by ShenGunNiTian** [maomao1996/Vue-mmPlayer#6]

**Comment by maomao1996** [comment]
你好，是在 [music.vue](https://github.com/maomao1996/Vue-mmPlayer/blob/master/src/pages/music.vue) 里面

**Comment by maomao1996** [comment]
滚动条目前是通过CSS改变的，具体样式请查看[index.less](https://github.com/maomao1996/Vue-mmPlayer/blob/master/src/assets/css/index.less)
