### ISSUE TITLE
search 错误

### ISSUE THREAD

**Issue by R2h1** [maomao1996/Vue-mmPlayer#68]
song.js:27 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at c (song.js:27:27)
    at song.js:53:18
    at Array.forEach (<anonymous>)
    at l (song.js:50:8)
    at search.vue:95:1

**Comment by maomao1996** [comment]
能提供下具体搜索的关键词吗因为接口返回的 `artists` 不是一个数组，

**Comment by R2h1** [comment]
***@***.***的自动回复邮件。已收到您的邮件！

**Comment by R2h1** [comment]
> 能提供下具体搜索的关键词吗 这是因为接口返回的 `artists` 不是一个数组，

试了很多关键词表现和这个一样（比如：毛不易）

**Comment by maomao1996** [comment]
我这边试了下是可以搜索的

https://netease-music.fe-mm.com/#/music/search

**Comment by R2h1** [comment]
谢谢，那应该是我这边的问题

**Comment by maomao1996** [comment]
你看下接口返回的歌手数据是 `artists` 还是 `ar`，不同的接口这个字段名不一样的
