### ISSUE TITLE
你好，我想问一下，为什么在本地直接打开那个html文件，可以直接播放歌曲，感觉有点神奇

### ISSUE THREAD

**Issue by ShenGunNiTian** [maomao1996/Vue-mmPlayer#7]

**Comment by maomao1996** [comment]
因为请求的是我的服务器，所以是可以直接播放的

**Comment by ShenGunNiTian** [comment]
原来是这样。对了想问一下，这个https://github.com/Hxiaodou/heiyaMusic，https://music.heiya123.com
怎么把歌曲、歌手、专辑这里的列表头固定住，和你的这个一样，

**Comment by maomao1996** [comment]
改下页面布局呗，把列表头和列表内容分开，不要放一个容器里面

**Comment by ShenGunNiTian** [comment]
好的谢谢了，这个好像用到插件 了，之前也试着改了一下，但没成功。搞着搞着都头晕了。。。
