### ISSUE TITLE
搜索转不出来，其他都正常

### ISSUE THREAD

**Issue by Winxpor** [maomao1996/Vue-mmPlayer#72]
请教一下大家是什么原因

**Comment by maomao1996** [comment]
> 请教一下大家是什么原因

可以先 f12 看下控制台

**Comment by Winxpor** [comment]
> > 请教一下大家是什么原因
> 
> 可以先 f12 看下控制台
![11](https://user-images.githubusercontent.com/92909625/199014124-3345b5d5-ad09-4905-9f36-0b7c0431808a.PNG)
我试了一下，musicData似乎只能读到id和name，从artists开始就全是undefined了/(ㄒoㄒ)/~~

**Comment by Winxpor** [comment]
> > > 请教一下大家是什么原因
> > 
> > 
> > 可以先 f12 看下控制台
> > ![11](https://user-images.githubusercontent.com/92909625/199014124-3345b5d5-ad09-4905-9f36-0b7c0431808a.PNG)
> > 我试了一下，musicData似乎只能读到id和name，从artists开始就全是undefined了/(ㄒoㄒ)/~~

解决啦，是因为网易云官方字段变更导致的
