### ISSUE TITLE
一个小小的提议

### ISSUE THREAD

**Issue by Request-timed-out** [maomao1996/Vue-mmPlayer#74]
现在有了访客人数，这个数字我之前一直以为是和我同时在听歌的人数。

加完差不多像这样，供参考：

`126 online` **mmPlayer 在线音乐播放器** `visitors 7334`

感谢你一直维护着这个项目！

**Comment by maomao1996** [comment]
感谢反馈，在线人数这个功能修改后台服务，在当前版本暂时不会添加；不过后面会加一个全屏歌词的功能 😃
