### ISSUE TITLE
运行$ npm run serve时[eslint]报错

### ISSUE THREAD

**Issue by sliencetree** [maomao1996/Vue-mmPlayer#79]
$ npm run serve

> vue-mmplayer@1.8.3 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Failed to compile with 1 error11:47:36

[eslint]
C:\Users\18700\Vue-mmPlayer\src\App.vue

**Comment by maomao1996** [comment]
我这边测试都没 `eslint` 错误，你的 `node` 版本是多少的

**Comment by sliencetree** [comment]
> 我这边测试都没 错误，你的 版本是多少的`eslint``node`

感谢回复！node版本18.14.2，eslint为8.34.4

**Comment by maomao1996** [comment]
> > 我这边测试都没 错误，你的 版本是多少的`` eslint``node ``
> 
> 感谢回复！node版本18.14.2，eslint为8.34.0

你把依赖删了重新装一下试试，我刚重新拉了安装依赖也没错
