### ISSUE TITLE
请问下顺序播放和列表循环有何区别？

### ISSUE THREAD

**Issue by gdutwyg** [maomao1996/Vue-mmPlayer#8]
![image](https://user-images.githubusercontent.com/11848087/53229414-132ed300-36bf-11e9-85d7-be5fd23835cb.png)
我在你代码里面看到是逻辑貌似是一样的

**Comment by gdutwyg** [comment]
明白了

**Comment by maomao1996** [comment]
这里 switch 逻辑是有点重复可以简化成
`  
  case playMode.listLoop:
  case playMode.order:
    list = this.orderList;
    break;
`

**Comment by gdutwyg** [comment]
![image](https://user-images.githubusercontent.com/11848087/53247382-2ad18000-36ee-11e9-8dcc-3e18acd0927f.png)
还有这里

```js
// 这样是否更好
this.isMute = percent === 0 ?  true : false;
```

**Comment by maomao1996** [comment]
还可以直接这样写的：

`this.isMute = percent === 0`

这个项目大多代码都是很久以前写的，很多都可以简化，等有空的时候会做一些代码上的优化的
