### ISSUE TITLE
你好可以加您qq或者微信，解答我一个问题吗

### ISSUE THREAD

**Issue by ffser** [maomao1996/Vue-mmPlayer#87]
我发现您的首页用的阿里的服务器而且还备案了，但是其他所以内容全部是国外的。我挺好奇的。可以加个联系方式给我解惑吗。我的qq250248410

**Comment by maomao1996** [comment]
只有个人主页为了备案才部署在阿里云服务器上，其他的作品都是通过网站托管平台 netlify 和 vercel 部署的，然后配置下自定义域名，联系方式我博客上有的
