### ISSUE TITLE
你好,我有个问题想请教一下

### ISSUE THREAD

**Issue by IsKaros** [maomao1996/Vue-mmPlayer#9]
你好,我自己也在做一个播放器,像网易云那样,但播放全部的功能真的把我快卡疯了- -我想用Vuex的actions做,写一个addSong获取一首歌除url之外的信息,再写一个addList,获取整个歌单的信息的,遍历整个歌单的id,执行addSong的方法,然后再写一个getUrl方法,获取当前应该播放的那首歌的url数据,再用state设置播放器显示.按照这样顺序执行,结果顺序总是不对,查了async/await,还是没开窍,可以交流一下吗

**Comment by maomao1996** [comment]
播放全部就是把当前列表的音乐替换掉正在播放列表里面的音乐，你获取音乐信息的时候可以在播放的时候再去获取，没必要一次性获取，获取到之后把这些信息缓存到 vuex 播放列表里面当前音乐的 data 里面，下次播放的时候先判断当前 data 有没有这些信息，没有再去请求接口，你这样一次获取下来你还要考虑其中某一两条获取失败的情况，还有插入顺序要一致这些等等，建议你还是播放前再去获取当前音乐的信息

**Comment by IsKaros** [comment]
谢谢你,我明白了

**Comment by bao2333** [comment]
你好 我想问一下你的播放器进度条是怎样适配移动端的  我用了一下你写的进度条组件  好像还是按照pc版来的 可以帮我解释一下吗

**Comment by maomao1996** [comment]
代码都差不多的，就是监听事件要加上移动端的 `touch` 事件，拖动距离改成 `e.touches[0].pageX`，其他的基本和 pc 的一样

**Comment by bao2333** [comment]
谢谢你 明白了
